#!/bin/bash
set -e

POSTGRESQL_SINGLE="sudo -u postgres $POSTGRESQL_BIN --single --config-file=$POSTGRESQL_CONFIG_FILE"

if [ ! -d $POSTGRESQL_DATA ]; then
  mkdir -p $POSTGRESQL_DATA
  chown -R postgres:postgres $POSTGRESQL_DATA
  sudo -u postgres /usr/lib/postgresql/9.4/bin/initdb -D $POSTGRESQL_DATA -E 'UTF-8' --lc-collate=$LANG --lc-ctype=$LANG
  ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem $POSTGRESQL_DATA/server.crt
  ln -s /etc/ssl/private/ssl-cert-snakeoil.key $POSTGRESQL_DATA/server.key
  chown -R postgres:postgres $POSTGRESQL_DATA/server.*
fi

sed -ri "s|^(ssl_cert_file\s=\s)\S+|\1'$POSTGRESQL_DATA/server.crt'|" $POSTGRESQL_CONFIG_FILE; grep -rn "ssl_cert_file" $POSTGRESQL_CONFIG_FILE
sed -ri "s|^(ssl_key_file\s=\s)\S+|\1'$POSTGRESQL_DATA/server.key'|" $POSTGRESQL_CONFIG_FILE; grep -rn "ssl_cert_file" $POSTGRESQL_CONFIG_FILE

$POSTGRESQL_SINGLE <<< "CREATE USER $POSTGRESQL_USER WITH SUPERUSER;" > /dev/null
$POSTGRESQL_SINGLE <<< "ALTER USER $POSTGRESQL_USER WITH PASSWORD '$POSTGRESQL_PASS';" > /dev/null
$POSTGRESQL_SINGLE <<< "CREATE DATABASE $POSTGRESQL_DB OWNER $POSTGRESQL_USER TEMPLATE $POSTGRESQL_TEMPLATE;" > /dev/null

exec sudo -u postgres $POSTGRESQL_BIN --config-file=$POSTGRESQL_CONFIG_FILE
